name: ETH Volume Turnover Scrape Automation Script

on:
  schedule:
    - cron: "30 16 * * *"  # Runs daily at 4:30 PM UTC (10:00 PM Sri Lankan time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas selenium beautifulsoup4

    - name: Run Scraper Script
      run: python eth_aum_volume_and_turnover_script.py

    - name: Commit and Push Changes
      run: |

        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        git add eth_volume_turnover_aum_data_new.csv
        git commit -m "Automated AUM Data Update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
